const OK = 200;
const CREATED = 201;
const ERROR_BAD_REQUEST = 400;
const ERROR_UNAUTHORIZATE = 401;
const FORBIDDEN = 403;
const ERROR_NOT_FOUND = 404;
const CONFLICT = 409;
const ERROR_INTERNAL_SERVER = 500;

module.exports = {
  OK,
  CREATED,
  ERROR_BAD_REQUEST,
  ERROR_UNAUTHORIZATE,
  FORBIDDEN,
  ERROR_NOT_FOUND,
  CONFLICT,
  ERROR_INTERNAL_SERVER,
};
